<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <Platforms>x64</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FFmpeg.AutoGen" Version="7.0.0" />
    <PackageReference Include="Sdcb.FFmpeg.runtime.windows-x64" Version="7.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\RemoteControl.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shared\FFmpegSetup.cs" Link="Media\FFmpegSetup.cs" />
    <Compile Include="..\Shared\UiKit.cs" Link="Ui\UiKit.cs" />
    <Page Include="..\Shared\Theme.xaml" Link="Theme.xaml" />
  </ItemGroup>

</Project>
