<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FFmpeg.AutoGen" Version="7.0.0" />
    <PackageReference Include="Sdcb.FFmpeg.runtime.windows-x64" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\Shared\FFmpegSetup.cs" Link="FFmpegSetup.cs" />
    <Compile Include="..\..\Server\H264Encoder.cs" Link="H264Encoder.cs" />
    <Compile Include="..\..\Client\H264Decoder.cs" Link="H264Decoder.cs" />
  </ItemGroup>

</Project>
